AcademiaAPP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('ficha/', include('ficha.urls', namespace='ficha')),
    path('palimentar/', include('palimentar.urls', namespace='palimentar')),
    path('clientes/', include('clients.urls', namespace='clients')),
    path('treino/', include('treino.urls', namespace='treino')),
    path('profissional/', include('profissional.urls', namespace='profissional')),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('alimento/', include('alimento.urls', namespace='alimento')),
    path('exercicio/', include('exercicio.urls', namespace='exercicio')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/exercicio/urls.py
from django.urls import path
from . import views

app_name = 'exercicio'

urlpatterns = [
    path('', views.list_exercicio, name='list_exercicio'),
    path('adicionar/<int:id_profissional>/', views.add_exercicio_item, name='add_exercicio'),
    path('excluir/<int:id_exercicio>/', views.delete_exercicio, name='delete_exercicio'),
    path('excluir-item/<int:id_exercicio_item>/', views.delete_exercicio_item, name='delete_exercicio_item'),
    path('adicionar-item/<int:id_exercicio>/', views.add_exercicio_item, name='add_exercicio_item'),
    path('editar-status/<int:id_exercicio>/', views.edit_exercicio_status, name='edit_exercicio_status'),
]

apps/profissional/urls.py
from django.urls import path
from . import views

app_name = 'profissional'

urlpatterns = [
    path('', views.list_profissional, name='list_profissional'),
    path('adicionar/', views.add_profissional, name='add_profissional'),
    path('editar/<int:id_profissional>/', views.edit_profissional, name='edit_profissional'),
    path('excluir/<int:id_profissional>/', views.delete_profissional, name='delete_profissional'),
]

apps/exercicio/models.py
from django.db import models
from treino.models import Treino
from profissional.models import Profissional

# Create your models here.

class Exercicio(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    total_price = models.FloatField('Preco Total', null=True, blank=True, default=0.0)
    STATUS_CHOICES = (
        ('Em andamento', 'Em andamento'),
        ('Finalizado', 'Finalizado'),
        ('Cancelado', 'Cancelado'),
    )
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES, null=True, blank=True, default='Em andamento')
    profissional = models.ForeignKey(Profissional, on_delete=models.CASCADE)
    exercicio_item = models.ManyToManyField(Treino, through='ExercicioItem', blank=True)
    
    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        ordering =['-created_on']

    def __str__(self):
        return "%s" % (self.total_price) 


class ExercicioItem(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    quantity = models.IntegerField('Quantidade',null=True, blank=True,default=0)
    unitary_price = models.FloatField('Preco unitario',null=True, blank=True, default=0.0)
    exercicio = models.ForeignKey(Exercicio, on_delete=models.CASCADE)
    treino = models.ForeignKey(Treino, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Item de Exercicio'
        verbose_name_plural = 'Itens de Exercicio'
        ordering =['id']

    def __str__(self):
        return "%s" % (self.quantity)

apps/exercicio/forms.py
from django import forms
from .models import Treino, Profissional, ExercicioItem ,Treino

class ExercicioForm(forms.ModelForm):
    
    class Meta:
        model = Treino
        exclude = ('profissional', 'created_on' , 'updated_on')

class ExercicioItemForm(forms.ModelForm):
    
    class Meta:
        model = ExercicioItem
        exclude = ('exercicio', 'created_on' , 'updated_on')

apps/exercicio/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ExercicioForm, ExercicioItemForm
from .models import Exercicio , ExercicioItem, Treino, Profissional

# Create your views here.

def add_exercicio(request, id_client):
    template_name = 'exercicio/add_exercicio.html'
    context = {}
    if request.method == 'POST':
        form = ExercicioForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.client = Profissional.objects.get(id=id_client)
            f.save()
            form.save_m2m()
            return redirect('exercicio:list_exercicio')
    form = ExercicioForm()
    context['form'] = form
    return render(request, template_name, context)

def list_exercicio(request):
    template_name = 'exercicio/list_exercicio.html'
    exercicio = Exercicio.objects.filter()
    exercicio_items = ExercicioItem.objects.filter()
    treino = Treino.objects.filter()
    profissional = Profissional.objects.filter()
    context = {
        'exercicio': exercicio,
        'exercicio_items': exercicio_items,
        'treinos': treino,
        'profissional': profissional
    }
    return render(request, template_name, context)

def delete_exercicio(request, id_exercicio):
    exercicio = Exercicio.objects.get(id=id_exercicio)
    exercicio.delete()
    return redirect('exercicio:list_exercicio')

def add_exercicio_item(request, id_exercicio):
    template_name = 'exercicio/add_exercicio_item.html'
    context = {}
    if request.method == 'POST':
        form = ExercicioItemForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.exercicio = Exercicio.objects.get(id=id_exercicio)
            f.save()
            form.save_m2m()
            return redirect('exercicio:list_exercicio')
    form = ExercicioItemForm()
    context['form'] = form
    return render(request, template_name, context)

def delete_exercicio_item(request, id_exercicio_item):
    exercicioitem = ExercicioItem.objects.get(id=id_exercicio_item)
    exercicioitem.delete()
    return redirect('exercicio:list_exercicio')

def edit_exercicio_status(request, id_exercicio):
    template_name = 'exercicio/edit_exercicio_status.html'
    context ={}
    exercicio = get_object_or_404(Exercicio, id=id_exercicio)
    if request.method == 'POST':
        form = ExercicioForm(request.POST, instance=exercicio)
        if form.is_valid():
            form.save()
            return redirect('exercicio:list_exercicio')
    form = ExercicioForm(instance=exercicio)
    context['form'] = form
    return render(request, template_name, context)

templates/exercicio/add_exercicio.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Pedido - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Deseja abrir um pedido? </b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-sm">Sim</button>   <a href="{% url 'profissional:list_profissional' %}" class="btn btn-primary btn-sm">Nao</a>     
                </form>
                
            </div>
        </div>
    </div>

{% endblock body %}

templates/exercicio/add_exercicio_item.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Item do Exercicio - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Adicionar Item do Exercicio</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.quantity.id_for_label }}">Quantidade</label>
                    {{ form.quantity|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.unitary_price.id_for_label }}">Preco Unitario</label>
                    {{ form.unitary_price|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.treino.id_for_label }}">Exercicio</label>
                    {{ form.treino|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/exercicio/edit_exercicio_status.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Item do Exercicio - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Alterar Status do Exercicio</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.status.id_for_label }}">Status</label>
                    {{ form.status|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Alterar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/exercicio/list_exercicio.html
{% extends 'base.html' %}

{% block title %}

    Lista de Exercicios - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Exercicios</b></h5>
        <div class="row">
            <div class ="col-md-12">
            <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Status</th>
                    <th scope="col">Cliente</th>
                    <th scope="col">Preco Total</th>
                    <th scope="col">Exercicio</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for exercicio in exercicio %}
                        <tr>
                            <th scope="row">
                                {% if exercicio.status == 'Finalizado' or exercicio.status == 'Cancelado' %}
                                    <p style="color:darkgray;" >{{ exercicio.id }}</p>
                                {% else %}
                                    {{ exercicio.id }}
                                {% endif %}
                            </th>
                            <td>
                                {% if exercicio.status == 'Finalizado' or exercicio.status == 'Cancelado' %}
                                    <p style="color:darkgray;" >{{ exercicio.status }}</p>
                                {% else %}
                                    {{ exercicio.status }}
                                {% endif %}
                            </td>
                            <td>
                                {% for client in clients %}
                                    {% if exercicio.client_id == client.id %}
                                        {% if exercicio.status == 'Finalizado' or exercicio.status == 'Cancelado' %}
                                            <p style="color:darkgray;" >{{ client.first_name }} {{ client.last_name }}</p>
                                        {% else %}
                                            {{ client.first_name }} {{ client.last_name }}
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}   
                            </td>
                            <td>
                                {% if exercicio.status == 'Finalizado' or exercicio.status == 'Cancelado' %}
                                    <p style="color:darkgray;" >R$ {{ exercicio.total_price }}</p>
                                {% else %}
                                    R$ {{ exercicio.total_price }}
                                {% endif %}
                            </td>
                            <td>
                                {% if exercicio.status == 'Finalizado' or exercicio.status == 'Cancelado' %}
                                    <a href="#" class="btn btn-primary btn-sm disabled">Adicionar itens</a>
                                {% else %}
                                    <a href="{% url 'exercicio:add_exercicio_item' exercicio.id %}" class="btn btn-primary btn-sm">Adicionar itens</a>
                                {% endif %}
                                <br /><br />
                                {% for exercicio_item in exercicio_items %}
                                    {% if exercicio_item.exercicio_id == exercicio.id %}
                                        Produto: {{ exercicio_item.product}}<br /> 
                                        Quantidade: {{ exercicio_item.quantity}}<br />
                                        Valor Unitario: R$ {{ exercicio_item.unitary_price }}<br />
                                        <a href="{% url 'exercicio:delete_exercicio_item' exercicio_item.id %}">Excluir Item</a><br /><br />
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                <a href="{% url 'exercicio:edit_exercicio_status' exercicio.id %}" class="btn btn-danger btn-sm ">Alterar Status</a>
                            </td>
                            <td>
                                <a href="{% url 'exercicio:delete_exercicio' exercicio.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}