AcademiaAPP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('ficha/', include('ficha.urls', namespace='ficha')),
    path('palimentar/', include('palimentar.urls', namespace='palimentar')),
    path('clientes/', include('clients.urls', namespace='clients')),
    path('treino/', include('treino.urls', namespace='treino')),
    path('profissional/', include('profissional.urls', namespace='profissional')),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('alimento/', include('alimento.urls', namespace='alimento')),
    path('exercicio/', include('exercicio.urls', namespace='exercicio')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('novo-usuario/',views.add_user, name='add_user'),
    path('login/',views.user_login, name='user_login'),
    path('sair/',views.user_logout, name='user_logout'),
    path('alterar-senha/',views.user_change_password, name='user_change_password'),
    path('alterar-usuario/<username>/',views.user_change_information, name='user_change_information'),
]

apps/clients/urls.py
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.list_clients, name='list_clients'),
    path('adicionar/', views.add_client, name='add_client'),
    path('editar/<int:id_client>/', views.edit_client, name='edit_client'),
    path('excluir/<int:id_client>/', views.delete_client, name='delete_client'),
    path('buscar/', views.search_clients, name='search_clients'),
]

apps/ficha/urls.py
from django.urls import path
from . import views

app_name = 'ficha'

urlpatterns = [
    path('', views.list_ficha, name='list_ficha'),
    path('adicionar/', views.add_ficha, name='add_ficha'),
    path('editar/<int:id_ficha>/', views.edit_ficha, name='edit_ficha'),
    path('excluir/<int:id_ficha>/', views.delete_ficha, name='delete_ficha'),
]

apps/treino/urls.py
from django.urls import path
from . import views

app_name = 'treino'

urlpatterns = [
    path('', views.list_treino, name='list_treino'),
    path('adicionar/', views.add_treino, name='add_treino'),
    path('editar/<int:id_treino>/', views.edit_treino, name='edit_treino'),
    path('excluir/<int:id_treino>/', views.delete_treino, name='delete_treino'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Academia App{% endblock title %}</title>
</head>
<body>
   <!-- INICIO: Bloco do Bootstrap a ser incluido -->
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Academia App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {% if user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarsExample05">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
                <div class="dropdown-menu" aria-labelledby="dropdown05">
                    <a class="dropdown-item" href="{% url 'clients:list_clients' %}
                    ">Clientes</a>
                    <a class="dropdown-item" href="{% url 'profissional:list_profissional' %}
                    ">Profissionais</a>
                    <a class="dropdown-item" href="{% url 'exercicio:list_exercicio' %}">Exercicios</a>
                    <a class="dropdown-item" href="{% url 'alimento:list_alimento' %}">Alimentos</a>
                    <a class="dropdown-item" href="{% url 'treino:list_treino' %}">Treinos</a>
                    <a class="dropdown-item" href="{% url 'ficha:list_ficha' %}
                    ">Fichas</a>
                    <a class="dropdown-item" href="{% url 'palimentar:list_palimentar' %}
                    ">Plano alimentar</a>
                </div>
            </li>
        </ul>
        <form action="{% url 'clients:search_clients' %}" method="GET" class="form-inline my-2 my-md-0" style="margin-right: 10px">
            <input class="form-control" name="query" type="text" placeholder="Pesquisar" aria-label="Buscar" style="margin-right: 10px">
            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Buscar</button>
        </form>
         <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.get_full_name|default:user.username }}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                    <a class="dropdown-item" href="{% url 'accounts:user_change_information' user.username %}">Conta</a>
                    <a class="dropdown-item" href="{% url 'accounts:user_change_password' %}">Trocar senha</a>
                    <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Sair</a>
                </div>
            </li>
        </ul>
    </div>
    {% endif %}
</nav>
<!-- FIM: Bloco do Bootstrap a ser incluido -->
    {% block body %}
    
    {% endblock body %}
    
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>