AcademiaAPP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('ficha/', include('ficha.urls', namespace='ficha')),
    path('palimentar/', include('palimentar.urls', namespace='palimentar')),
    path('clientes/', include('clients.urls', namespace='clients')),
    path('treino/', include('treino.urls', namespace='treino')),
    path('profissional/', include('profissional.urls', namespace='profissional')),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('alimento/', include('alimento.urls', namespace='alimento')),
    path('exercicio/', include('exercicio.urls', namespace='exercicio')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/exercicio/urls.py
from django.urls import path
from . import views

app_name = 'exercicio'

urlpatterns = [
    path('', views.list_exercicio, name='list_exercicio'),
    path('adicionar/<int:id_profissional>/', views.add_exercicio_item, name='add_exercicio'),
    path('excluir/<int:id_exercicio>/', views.delete_exercicio, name='delete_exercicio'),
    path('excluir-item/<int:id_exercicio_item>/', views.delete_exercicio_item, name='delete_exercicio_item'),
    path('adicionar-item/<int:id_exercicio>/', views.add_exercicio_item, name='add_exercicio_item'),
    path('editar-status/<int:id_exercicio>/', views.edit_exercicio_status, name='edit_exercicio_status'),
]

apps/profissional/urls.py
from django.urls import path
from . import views

app_name = 'profissional'

urlpatterns = [
    path('', views.list_profissional, name='list_profissional'),
    path('adicionar/', views.add_profissional, name='add_profissional'),
    path('editar/<int:id_profissional>/', views.edit_profissional, name='edit_profissional'),
    path('excluir/<int:id_profissional>/', views.delete_profissional, name='delete_profissional'),
]

apps/profissional/models.py
from django.db import models
from django.db import models
from palimentar.models import Palimentar

# Create your models here.
class Profissional(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    first_name = models.CharField('Nome', max_length=50)
    last_name = models.CharField('Sobrenome', max_length=100) 
    address = models.CharField('Endereco', max_length=200)   
    cell_phone = models.CharField('Telefone celular', max_length=20)
    email = models.EmailField('E-mail',null=False, blank=False)
    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro'),
    )
    gender = models.CharField('Genero', max_length=1, choices=GENDER_CHOICES)
    profissional_palimentar = models.ManyToManyField(Palimentar, through='ProfissionalPalimentar', blank=True)
    
    class Meta:
        verbose_name = 'Profissional'
        verbose_name_plural = 'Profissional'
        ordering =['id']

    def __str__(self):
        return self.first_name
    
class ProfissionalPalimentar(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    Profissional = models.ForeignKey(Profissional, on_delete=models.CASCADE)
    palimentar = models.ForeignKey(Palimentar, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Item de Plano alimentar'
        verbose_name_plural = 'Itens de Plano alimentar'
        ordering =['id']

    def __str__(self):
        return self.palimentar.name

apps/profissional/forms.py
from django import forms
from .models import Profissional

class ProfissionalForm(forms.ModelForm):

    class Meta:
        model = Profissional
        exclude = ('created_on' , 'updated_on',)

apps/profissional/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ProfissionalForm
from .models import Profissional, Palimentar, ProfissionalPalimentar
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required(login_url='/contas/login/')
def add_profissional(request):
    template_name = 'profissional/add_profissional.html'
    context = {}
    if request.method == 'POST':
        form = ProfissionalForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('profissional:list_profissional')
    form = ProfissionalForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_profissional(request):
    template_name = 'profissional/list_profissional.html'
    profissional_palimentar = ProfissionalPalimentar.objects.filter()
    palimentar = Palimentar.objects.filter()
    profissional = Profissional.objects.filter()
    context = {
        'profissional': profissional,
        'palimentar': palimentar,
        'profissional_palimentar': profissional_palimentar
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_profissional(request, id_profissional):
    template_name = 'profissional/add_profissional.html'
    context ={}
    profissional = get_object_or_404(Profissional, id=id_profissional)
    if request.method == 'POST':
        form = ProfissionalForm(request.POST, instance=profissional)
        if form.is_valid():
            form.save()
            return redirect('profissional:list_profissional')
    form = ProfissionalForm(instance=profissional)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_profissional(request, id_profissional):
    profissional = Profissional.objects.get(id=id_profissional)
    profissional.delete()
    return redirect('profissional:list_profissional')

templates/profissional/add_profissional.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Profissional - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Registro do Funcionário</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.first_name.id_for_label }}">Nome</label>
                   {{ form.first_name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
                    {{ form.last_name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.address.id_for_label }}">Endereco</label>
                    {{ form.address|add_class:"form-control" }}
                </div>
                <div class="form-group">
                  <label for="{{ form.cell_phone.id_for_label }}">Telefone</label>
                  {{ form.cell_phone|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">E-mail</label>
                    {{ form.email|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.gender.id_for_label }}">Genero</label>
                    {{ form.gender|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/profissional/list_profissional.html
{% extends 'base.html' %}

{% block title %}

    Lista de Profissional - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista dos Profissionais</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'profissional:add_profissional' %}">Cadastro dos novos Profissionais</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Sobrenome</th>
                    <th scope="col">Endereco</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">Genero</th>
                    <th scope="col">Plano alimentar</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for profissional in profissional %}
                        <tr>
                            <th scope="row">{{ profissional.id }}</th>
                            <td>{{ profissional.first_name }}</td>
                            <td>{{ profissional.last_name }}</td>
                            <td>{{ profissional.address }}</td>
                            <td>{{ profissional.cell_phone }}</td>
                            <td>{{ profissional.email }}</td>
                            <td>{{ profissional.gender }}</td>
                            <td>
                                {% for profissional_palimentar in profissional_palimentar %}
                                    {% if profissional_palimentar.profissional_id == profissional.id %}
                                        <li>{{ profissional_palimentar.palimentar }}</li>
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                <a href="{% url 'profissional:edit_profissional' profissional.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>
                                <a href="{% url 'profissional:delete_profissional' profissional.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                            <td>   
                                 <a href="{% url 'exercicio:add_exercicio' profissional.id %}" class="btn btn-danger btn-sm ">Pedir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}